#############################################
### PARA EXECUTAR NO AMBIENTE DE FEAT ###
#############################################
#
# Este arquivo configura o Google Cloud Build para enviar o código do otimizador para o ambiente FEAT do GCP.
# O build da imagem Docker será feito na nuvem, a imagem será publicada no Container Registry com a
# TAG "southamerica-east1-docker.pkg.dev/sz-academia-digital-feat/qs-chatbot/qs-chatbot:latest", que é a TAG utilizada pela VM para buscar a última
# versão da imagem do otimizador e executá-la no Google Compute Engine
#
# Para fazer o Build, será necessário instalar o gcloud SDK (https://cloud.google.com/sdk/docs/install).
# Em seguida, basta executar os comandos abaixo dentro da pasta 'qs-chatbot':
#
# gcloud auth login
# gcloud auth application-default login
# gcloud config set project sz-academia-digital-feat
# gcloud auth application-default print-access-token
# gcloud builds submit . --config=cloudbuild_exec_on_feat.yaml --ignore-file=.dockerignore --substitutions _TOKEN_SA=[TOKEN GERADO NO PASSO ANTERIOR]

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile',
          '--build-arg', 'PROJECT_ID=sz-academia-digital-feat',
          '--build-arg', 'SECRET_ID=academia_dig_client_id',
          '--build-arg', 'TOKEN_SA=${_TOKEN_SA}',
          '-t', 'southamerica-east1-docker.pkg.dev/sz-academia-digital-feat/qs-chatbot/qs-chatbot:latest', '.']
images: ['southamerica-east1-docker.pkg.dev/sz-academia-digital-feat/qs-chatbot/qs-chatbot:latest']